//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lista3 {
    
    public partial class ApiDemo {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.Literal RequestHeadersLiteral;
        
        protected global::System.Web.UI.WebControls.Label lblResponseHeaderInfo;
        
        protected global::System.Web.UI.WebControls.Literal MappedPathLiteral;
        
        protected global::System.Web.UI.WebControls.Literal HttpContextInfoLiteral;
    }
}
