//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lista3 {
    
    public partial class Containers {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.Label lblApp;
        
        protected global::System.Web.UI.WebControls.Button btnIncApp;
        
        protected global::System.Web.UI.WebControls.Label lblSession;
        
        protected global::System.Web.UI.WebControls.Button btnIncSession;
        
        protected global::System.Web.UI.WebControls.Label lblItems;
        
        protected global::System.Web.UI.WebControls.Button btnTransferWithItems;
        
        protected global::System.Web.UI.WebControls.Label lblSingleton;
        
        protected global::System.Web.UI.WebControls.Button btnCreateSingleton;
    }
}
